# Generated by Django 5.0.7 on 2024-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='auther_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='auther_id',
            field=models.ManyToManyField(blank=True, to='blog.author'),
        ),
    ]
