# Generated by Django 5.0.7 on 2024-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_video_category_image_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='courses/'),
        ),
    ]
