# Generated by Django 5.0.7 on 2024-07-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_blogcomment_coursecomment_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
