# Generated by Django 5.0.7 on 2024-07-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=300)),
            ],
        ),
    ]
