# Generated by Django 5.0.7 on 2024-08-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
