# Generated by Django 5.0.7 on 2024-08-01 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_coursecomment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
