# Generated by Django 5.0.7 on 2024-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursecomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
