# Generated by Django 5.0.7 on 2024-08-01 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.student'),
        ),
    ]
